# Generated by Django 5.1.3 on 2024-11-08 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('custname', models.CharField(max_length=350)),
                ('custnumb', models.IntegerField(blank=True, default=0, null=True)),
                ('custemail', models.EmailField(blank=True, max_length=254, null=True)),
                ('totalitem', models.IntegerField(default=0)),
                ('totalprice', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('per_discount', models.IntegerField(default=0)),
                ('payprice', models.IntegerField(default=0)),
                ('itemcode', models.CharField(max_length=50)),
                ('payment', models.CharField(choices=[('1', 'Cash'), ('2', 'Online'), ('3', 'Pending')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='invoiceitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('itemname', models.CharField(blank=True, max_length=350, null=True)),
                ('itemsize', models.CharField(max_length=50)),
                ('itemprice', models.FloatField(default=0)),
                ('itemquntity', models.IntegerField(default=0)),
                ('itemtotal', models.FloatField(default=0)),
                ('itemcode', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=350)),
                ('size', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('totalquantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Inactive')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='stockhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('itemname', models.CharField(blank=True, max_length=350, null=True)),
                ('itemsize', models.CharField(max_length=50)),
                ('itemquntity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('1', 'Stock in'), ('2', 'Stock out')], default=1, max_length=2)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tempitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tempname', models.CharField(blank=True, max_length=350, null=True)),
                ('tempsize', models.CharField(max_length=50)),
                ('tempprice', models.FloatField(default=0)),
                ('tempquntity', models.IntegerField(default=0)),
                ('temptotal', models.FloatField(default=0)),
            ],
        ),
    ]
